import sequelize from '../../../db/sql';
import { DataTypes } from 'sequelize';

const DmNhanVien = sequelize.define(
  'dmnhanvien',
  {
    manv: { type: DataTypes.INTEGER, primaryKey: true, allowNull: false },
    tennv: { type: DataTypes.STRING, allowNull: false },
    tenthuonggoi: { type: DataTypes.STRING },
    maphai: { type: DataTypes.INTEGER, allowNull: false },
    ngaysinh: { type: DataTypes.DATE },
    noisinh: { type: DataTypes.STRING },
    madantoc: { type: DataTypes.INTEGER },
    maquoctich: { type: DataTypes.INTEGER },
    chungchinghe: { type: DataTypes.STRING },
    machamcong: { type: DataTypes.STRING },
    chungminhthu: { type: DataTypes.STRING },
    ngaycapcmt: { type: DataTypes.DATE },
    noicapcmt: { type: DataTypes.STRING },
    tongiao: { type: DataTypes.STRING },
    makk: { type: DataTypes.INTEGER, allowNull: false },
    machuyenmon: { type: DataTypes.INTEGER, allowNull: false },
    email: { type: DataTypes.STRING },
    dienthoai: { type: DataTypes.STRING },
    anh1: { type: DataTypes.BLOB },
    anh2: { type: DataTypes.BLOB },
    sonhanhuyenquan: { type: DataTypes.STRING },
    mapxnguyenquan: { type: DataTypes.INTEGER },
    maqhnguyenquan: { type: DataTypes.INTEGER },
    mattnguyenquan: { type: DataTypes.INTEGER },
    sonhahokhau: { type: DataTypes.INTEGER },
    mapxhokhau: { type: DataTypes.INTEGER },
    maqhhokhau: { type: DataTypes.INTEGER },
    matthokhau: { type: DataTypes.INTEGER },
    sonhathuongtru: { type: DataTypes.INTEGER },
    mapxthuongtru: { type: DataTypes.INTEGER },
    maqhthuongtru: { type: DataTypes.INTEGER },
    mattthuongtru: { type: DataTypes.INTEGER },
    viettel: { type: DataTypes.STRING },
    soca: { type: DataTypes.INTEGER },
    sotaikhoan: { type: DataTypes.STRING },
    tennganhang: { type: DataTypes.STRING },
    chinhanh: { type: DataTypes.STRING },
    macu: { type: DataTypes.STRING },
    machucdanh: { type: DataTypes.INTEGER },
    uservnpt: { type: DataTypes.STRING },
    passvnpt: { type: DataTypes.STRING },
    nghiviec: { type: DataTypes.BOOLEAN },
    tentruc: { type: DataTypes.STRING },
    tn: { type: DataTypes.STRING },
    KL: { type: DataTypes.BOOLEAN },
    khongchamcong: { type: DataTypes.BOOLEAN },
    sapxepchamcong: { type: DataTypes.INTEGER },
    manvhienthi: { type: DataTypes.STRING },
    maroche: { type: DataTypes.STRING },
    ngaycapcc: { type: DataTypes.DATE },
    tungaycc: { type: DataTypes.DATE },
    denngaycc: { type: DataTypes.DATE },
    machucvu: { type: DataTypes.INTEGER },
    madonnguyen: { type: DataTypes.INTEGER },
    loaihoso: { type: DataTypes.INTEGER },
  },
  {
    timestamps: false,
  }
);

export default DmNhanVien;
